-- MySQL Script generated by MySQL Workbench
-- Tue Jul 14 23:03:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `poste` VARCHAR(45) NULL,
  `zone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Risque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Risque` (
  `idRisque` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `photo` VARCHAR(45) NULL,
  `localisation` TEXT(80) NULL,
  `description` TEXT(80) NULL,
  `caracterisation` TEXT(80) NULL,
  `evaluation` TEXT(80) NULL,
  `mesureComp` TEXT(80) NULL,
  `mesurePre` TEXT(80) NULL,
  `date` DATETIME NULL,
  `emailRespon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRisque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserRisque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserRisque` (
  `User_idUser` INT UNSIGNED NOT NULL,
  `Risque_idRisque` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`User_idUser`, `Risque_idRisque`),
  INDEX `fk_User_has_Risque_Risque1_idx` (`Risque_idRisque` ASC) VISIBLE,
  INDEX `fk_User_has_Risque_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Risque_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Risque_Risque1`
    FOREIGN KEY (`Risque_idRisque`)
    REFERENCES `mydb`.`Risque` (`idRisque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
